spring:
  config:
    activate:
      on-profile: local
---
spring:
#  mvc:
#    servlet:
#      path: /api
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
  docker:
    compose:
      enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: dn47gh3y
    url: jdbc:mysql://localhost:3306/aperturearena?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true
logging:
  level:
    org:
      springframework:
        security: DEBUG
